package DAOFactory;

public class ParaQueServiraEstePacote {
	
	// DEPOIS DO PROJETO ESTAR QUASE PRONTO NESTA PARTE SERÁ COLOCADO OS NEGOCIOS
	// DO DAOFACTORY
	// 3 BJS, PASSAR BEM. 
	
	 // IDEIA POLIMORFISMO
	// ENTRADA E SAIDA

}
